name = "MakieTeX"
uuid = "6d554a22-29e7-47bd-aee5-0c5f06619414"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>, and contributors"]
version = "0.4.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Ghostscript_jll = "61579ee1-b43e-5ca0-a5da-69d92c66a64b"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Poppler_jll = "9c32591e-4766-534b-9725-b71a8799265b"
Rsvg = "c4c386cf-5103-5370-be45-f3a111cca3b8"
Typst_jll = "eb4b1da6-20f6-5c66-9826-fdb8ad410d0e"
tectonic_jll = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[extensions]
MakieTeXCairoMakieExt = "CairoMakie"
MakieTeXGLMakieExt = "GLMakie"
MakieTeXWGLMakieExt = "WGLMakie"

[compat]
Cairo = "1.0.5"
CairoMakie = "0.11, 0.12"
Colors = "0.9, 0.10, 0.11, 0.12"
DocStringExtensions = "0.8, 0.9"
Ghostscript_jll = "9"
Glib_jll = "2"
LaTeXStrings = "1"
Makie = "0.20, 0.21"
Poppler_jll = "21.9, 22, 23"
Rsvg = "1"
julia = "1.9"
Typst_jll = "0"
tectonic_jll = "0"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[targets]
test = ["Test", "Downloads", "CairoMakie", "GLMakie", "WGLMakie"]
